#model: "resnet50"
#output_stride: 50
segmentation_threshold: 0.7
blur: 5
erode: 10
dilate: 15
virtual_video_device: "/dev/video2"
real_video_device: "/dev/video0"
average_masks: 2
layers:
  - "empty": [["image", "images/background.jpg"]]
    #  - "foreground": ["match_hist"]
  - "foreground": []
